### ISSUE TITLE
Button in column

### ISSUE THREAD

**Issue by mcallistertyler** [imballinst/react-bs-datatable#124]
Hi, is there a way to add a column of buttons within the table? Similar to the example with the checkboxes.

Thanks

**Comment by imballinst** [comment]
Hello @mcallistertyler! There are 2 ways to do it:

1. The first one is to declare it using `cell` and have the list of headers outside of the component (so it is always static): https://codesandbox.io/s/3-0-1-buttons-in-table-example-fir1fw?file=/src/App.js
2. The second one is a bit more dynamic -- in case you want some external states to affect the button's behavior: https://codesandbox.io/s/3-0-1-buttons-in-table-example-with-dynamic-one-uvhn1x?file=/src/App.js

Let me know if there are parts that I can explain more!

**Comment by mcallistertyler** [comment]
Exactly what I was looking for, thanks for these examples - very helpful and clear 👍
