### ISSUE TITLE
Specify a className for a row based on the contents of the row

### ISSUE THREAD

**Issue by Susan123456789** [imballinst/react-bs-datatable#132]
I need the ability to add a className to a row based on the contents of the row (for example, to change the color of the row based on the value in a specific column).  Similar to the [cellProps](https://github.com/imballinst/react-bs-datatable/blob/main/api/interfaces/helpers_types.TableColumnType.md#cellprops)  but for adding a className to the row instead of the column.  Is this possible?

Thanks!

**Comment by imballinst** [comment]
Hi @Susan123456789, thanks for using this library!

That is not possible at the moment, but I think I can work on this... some times today or tomorrow. I will get back to this issue after I finish it and let you know. Cheers!

**Comment by imballinst** [comment]
Hi @Susan123456789, please take a look at `react-bs-datatable@3.3.0`. We can now add custom props to table rows, something like this:

```jsx
<TableBody
  rowProps={(row) => {
    return {
      style: {
        background: `rgba(128, 0, 0, ${row.score / 200})`
      }
    };
  }}
/>
```

![image](https://user-images.githubusercontent.com/7077157/161257658-4a3c4e69-93cc-4f8d-990a-da8274fbc352.png)

Example sandbox: https://codesandbox.io/s/react-bs-datatable-3-3-conditional-row-props-832ze3?file=/src/App.js. Example in Storybook: https://imballinst.github.io/react-bs-datatable/?path=/story/uncontrolled--custom-table-row-props.

Let me know if there are anything more that I can help with!

**Comment by Susan123456789** [comment]
Works perfectly!!  Thank you so much for the prompt response!!

**Comment by pullelakalyani** [comment]
Hey @imballinst does it work for column too?

**Comment by pullelakalyani** [comment]
@imballinst  Kudos!
I need the same that have it has i.e the styles one for the column and it works like a charm 😍

**Comment by pullelakalyani** [comment]
Hey @imballinst 
can we add spinner for the rowProps based on some conditions?

**Comment by imballinst** [comment]
@pullelakalyani I don't think we can add the moment... what is the use-case?

**Comment by pullelakalyani** [comment]
Ohh okay,
So its an ML usecase where the data take sometime to complete its tasks and update the records in the DB so when the ML process executes its tasks we can have the spinner spinning on a particular row based on the ML status

**Comment by imballinst** [comment]
Ah, I see. Yes, that makes sense. It requires quite a bit of API change, I think. Something like this:

```jsx
<TableBody>
  {data.map(row => {
    if (row.status === 'loading') {
      return <tr><td colSpan={headers.length}><Spinner /></td></tr>
    }

    return <TableRow row={row} />
  })}
</TableBody>
```

Not sure if it makes sense... but it's an option. What do you think?
