### ISSUE TITLE
Linking an entry to another page

### ISSUE THREAD

**Issue by chasen-bettinger** [Imballinst/react-bs-datatable#15]
Thanks for your superb work on this data table library. 

I would like to link each row to its own page. I didn't see this function in the documentation so I thought I would ask. I assume if I want that feature I would need to fork and add it?

**Comment by chasen-bettinger** [comment]
Hmm.. I don't really want to link the _cell_, I want to link the _row_.

For example in lines 25-27 in `BodyRow.js`, I want to wrap that in a link.

`Current`

```
 <tr className="tbody-tr-default">
      {row}
</tr>
```

`Desired`

```
<Link to={data.link}>
   <tr className="tbody-tr-default">
      {row}
   </tr>
</Link>
```

**Comment by Imballinst** [comment]
aaah, I see, my bad. yeah, currently there's no functionality for it (row linking) yet.

I think you can use the same style like the `cell` property and replace line 24-28 of `BodyRow.js` with this:

```
const rowWrapper = tableHeader[i].row;
const baseRow = (
  <tr className="tbody-tr-default">
    {row}
  </tr>
);

if (rowWrapper === undefined) {
  return baseRow;
} else {
  return rowWrapper(baseRow);
}
```

That way, it will be more flexible to wrap it with anything, not only just `<Link>` tags, IMO. I'm not sure whether to wrap the `<tr>` or wrap its children, though. What do you think?

**Comment by chasen-bettinger** [comment]
@Imballinst 
I could try it out and make a pull request. Does that sound like a good plan of action?

**Comment by Imballinst** [comment]
I think it does, thanks!

**Comment by Imballinst** [comment]
Fixed in https://github.com/Imballinst/react-bs-datatable/pull/53.
