### ISSUE TITLE
How to add buttons to rows/body e.g Edit button?

### ISSUE THREAD

**Issue by hefhem** [imballinst/react-bs-datatable#153]
Hi,

Please how can I add button or other actions at the row level. e.g. Edit button.

Thanks in advance

**Comment by hefhem** [comment]
Never mind I found it here 
https://codesandbox.io/s/fir1fw?file=/src/App.js:662-829

**Comment by imballinst** [comment]
hello @hefhem, I'm glad you sorted it out!

To prevent this from happening in the future, I have added the example to the Sandbox from the README as well: https://codesandbox.io/s/react-bs-datatable-3-typescript-bn234b?file=/src/App.tsx. Hopefully this can improve the developer experience.
