### ISSUE TITLE
Allow access to React event object for `onRowClick`

### ISSUE THREAD

**Issue by Thomas-Boi** [imballinst/react-bs-datatable#161]
Hi @imballinst,

I really like your package and find it very useful. I'd like to request one thing though: for the `onRowClick` callback, it'd be great if the React `event` object is passed in as a parameter.

```
onRowClick = function(rowData, event) {}
```

I need access to the `target` object of a click event and unfortunately, this is not allowing me to do so. I even consider overriding the `onRowClick` callback but it seems like passing in `onclick` via `rowProps` won't achieve what I want.
![image](https://user-images.githubusercontent.com/43018778/223297791-2de61e67-b8a3-4f9f-b13d-73c6ca8cf9a4.png)

It'd be great if you make the `onRowClick` callback accept a `event` argument. I can even do it myself via a MR if you would like that. However, since it's a small change, I thought perhaps you can add it in to another release.

![image](https://user-images.githubusercontent.com/43018778/223297892-0ed6f2e0-f2de-4b4e-bb11-ad145483a590.png)

Thank you for your time and I'd like to see this feature soon.

**Comment by imballinst** [comment]
hi @Thomas-Boi, thanks for using this library! I think that's a valid feature request, I'll see what I can do today and yes, this API looks good to me!

```js
onRowClick = function(rowData, event) {}
```

I'll get back to to you after I have published the beta version of the feature so that you could test it.

**Comment by imballinst** [comment]
hi @Thomas-Boi, I have published `3.7.0-beta.0` and here is the demo: https://codesandbox.io/s/keen-cartwright-9xph1b?file=/src/App.tsx. Feel free to play around and let me know if there are things that are still missing!

If all are good, then I'll merge the PR and publish 3.7.0.

**Comment by Thomas-Boi** [comment]
Thanks so much @imballinst for getting this done so quickly! I tested the feature and it works as expected. This would help me a lot with dynamically rendering some components via `createPortal` and absolute positing.

**Comment by Thomas-Boi** [comment]
One thing I've noticed though: the button `onclick` would need to manually call `event.stopPropagation` to prevent double event handler. This is fine with me and I'll just leave this comment here as documentations for future users.

**Comment by imballinst** [comment]
3.7.0 has been published to npm: https://www.npmjs.com/package/react-bs-datatable/v/3.7.0
