### ISSUE TITLE
Add `event` object to `onCheckboxChange`

### ISSUE THREAD

**Issue by Thomas-Boi** [imballinst/react-bs-datatable#164]
Hi @imballinst,

Thank you again for your previous fix. This time, I'd like to request you to add the `event ` object to the `onCheckboxChange` callback. I'm running into this problem for my code:

1. Add a `onRowClick` to my table.
2. Turn on the checkbox option for one of the rows.
3. Clicking on the checkbox would bubble up the event for the row `onclick` => it also triggers a `onRowClick` that I don't want

Having a `event` to `event.stopPropagation()` would be great for me to address this issue. I believe you can add it [here](https://github.com/imballinst/react-bs-datatable/blob/23c9527/src/components/TableBody.tsx#L156) and maybe anywhere else where the event handler is added. 

Thank you again for your time.

**Comment by imballinst** [comment]
hi @Thomas-Boi! Sounds good, I will do these on the next update:

1. Add event to the `onCheckboxChange`
2. Probably for safety measures, I'll add the `event.stopPropagation` on both `onRowClick` and `onCheckboxChange`.

Thanks for the idea!

**Comment by imballinst** [comment]
hi @Thomas-Boi, I have published the beta version: https://www.npmjs.com/package/react-bs-datatable/v/3.8.0-beta.1. Demo can be checked here: https://codesandbox.io/s/youthful-nova-cky9u9?file=/src/App.tsx

Also, I wasn't able to fix the bubbling thingy by `stopPropagation`. For some reasons, the row on click always gets called first (IIRC stopPropagation only works if it's the children event that's fired first). So I [worked it around](https://github.com/imballinst/react-bs-datatable/pull/165/files#diff-1bb46637c3eff0c840e4f4332247a5c03d8e11d9e6c7968503c750db2febac90R314) by checking if the clicked part of the row is either `<tr>` or `<td>`.

Let me know if there are things that's still missing. Thanks!

**Comment by imballinst** [comment]
@Thomas-Boi 3.8.0 has been published --> https://www.npmjs.com/package/react-bs-datatable/v/3.8.0. Feel free to re-open or create new issue if there are more issues/requests that you'd like to post. Thanks!
