### ISSUE TITLE
Add ability to reset checkboxes

### ISSUE THREAD

**Issue by Thomas-Boi** [imballinst/react-bs-datatable#168]
Hello,

Thank you for your work on this! I'd like to request a feature to reset the checkbox state to be all empty aka `none-selected`. I've been looking into `Controlled` components in the `__stories__` folder to control the state of the checkbox.

![image](https://user-images.githubusercontent.com/43018778/227405713-2e9f5557-62ae-4817-94cb-75d7d6ef5c56.png)

I tried to replicate what you did but with a `checkboxState` and a `onCheckboxChange`:
![image](https://user-images.githubusercontent.com/43018778/227406997-8d82ce29-7981-4c4c-92ca-e906ebb0ee88.png)

![image](https://user-images.githubusercontent.com/43018778/227407196-915b8e26-97a3-496a-af02-590fecaf13dc.png)

The `checkboxState` works as expected. However, the `onCheckboxChange` doesn't. When I click on a checkbox, there's no `console.log`. I tried with and without `useCallback` like the in story but nothing happened. 

I'm a bit worried with implementing a custom `onCheckboxChange` as well. After looking at the code, it looks like the callback would override the default behaviour:
![image](https://user-images.githubusercontent.com/43018778/227406449-146a3a67-edcd-4441-9f84-f98cf87a958a.png)

I'm worried that once I override it, I won't be able to handle the state change since the code looks complex to me. Perhaps there is an easier way to reset the checkbox state? I can hook into the checkbox state via `useDataTableWrapper`. Perhaps we can expose a method there to set the checkbox state?

If the only way is to override `onCheckboxChange`, perhaps you can expose the default version of `onCheckboxChange`? I noticed these lines in `DatatableWrapper.tsx` but I'm not sure whether `onCheckboxChange` is the default handler or the one I've overridden.
![image](https://user-images.githubusercontent.com/43018778/227406717-0f93265d-7232-4489-af05-42cc4720dbb9.png)

Thank you for your time and effort!

**Comment by Thomas-Boi** [comment]
Hi @imballinst , thanks for getting back to me so quickly!

I've made a sandbox [here](https://codesandbox.io/s/nervous-archimedes-0etchr). My use case is pretty simple:

- I have a DataTable displaying my data.
- The user can select rows using the checkboxes.
- I'd like a custom button that clear all the user's selection.

In the example, I've set `initialState` to `all-selected` and you can see that the checkbox in the header is selected. However, the `onChange` callback doesn't log anything to the console when I click on them.

I know that there's a `BulkCheckboxControl`. However, I'd like to have my own styled button to clear the selections.

If possible, I'd just like to have a function just for resetting the state. I've find that the default works great out of the box (store across data updates etc.) so I would prefer not to mess anything up by accident.

**Comment by imballinst** [comment]
Gotcha @Thomas-Boi, thanks for the thorough explanation and the sandbox! I think I understand it clearer now. I'll see what I can do this weekend then I'll get back to this issue with some PoCs.

**Comment by Thomas-Boi** [comment]
Thank you! I don't need anything fancy. If the best solution is to make it a controlled component, that's fine with me as long as I can still hook into the default functionality when needed.

**Comment by imballinst** [comment]
hi @Thomas-Boi, I have published https://www.npmjs.com/package/react-bs-datatable/v/3.9.0-beta.0 and I have made the sandbox here: https://codesandbox.io/s/white-microservice-s0bs6h?file=/src/App.js. Note that this example is uncontrolled table, so you don't actually need to make it controlled.

So I created this new function called `useTableCheckboxState`. It returns an object, one of the fields is `createBulkCheckboxClickHandler`. Here's how to use it:

```tsx
const { createBulkCheckboxClickHandler } = useTableCheckboxState();

return (
  <>
    <button
      onClick={createBulkCheckboxClickHandler("add", {
        idProp: "id",
        checkboxProp: "checkbox"
      })}
    >
      Add all to selection
    </button>

    <button
      onClick={createBulkCheckboxClickHandler("remove", {
        idProp: "id",
        checkboxProp: "checkbox"
      })}
    >
      Clear selection
    </button>
  </>
);
```

Let me know what you think about it. Thanks!

**Comment by Thomas-Boi** [comment]
Hi @imballinst this looks and works like what I wanted 👍 . As for naming, `useCreateCheckboxHandlers` seems more specific compared to `useTableCheckboxState` since this is specifically about handling checkboxes. However, I think either one is fine.

**Comment by imballinst** [comment]
Sounds good, thanks for the confirmation @Thomas-Boi! `useCreateCheckboxHandlers` it is. I will tweak the PR, merge it, then publish `3.9.0`.

**Comment by Thomas-Boi** [comment]
Thanks again on getting this done so quickly 😄

**Comment by imballinst** [comment]
Done! https://www.npmjs.com/package/react-bs-datatable/v/3.9.0. Tested in the sandbox as well for `3.9.0`: https://codesandbox.io/s/zen-platform-pq0ud0.

Please let me know if you have other questions. Thanks!
