### ISSUE TITLE
Documentation: `data[rowIdx] is undefined` when creating custom rows

### ISSUE THREAD

**Issue by Thomas-Boi** [imballinst/react-bs-datatable#170]
Hello @imballinst ,

I found a problem that I missed during testing. When I render the rows using custom rows (see [this sandbox](https://codesandbox.io/s/nervous-archimedes-0etchr?file=/src/App.js), line 44 and 56, the checkbox will fail when I click them. After looking through the code, I found that adding `rowIdx` will fix the problem.

*Suggested Solution*
This only happens during customization so it should be up to the user to address it. However, it'd be great if there's a Intellisense warning from Typescript that `rowIdx` is required. Updating the code docs might be necessary since this only break when checkbox is clicked and `rowIdx` is not provided. If I don't have checkboxes, the rows are rendered fine. I'll leave it up to you on how best to handle this.

*Current jsdoc with no `rowIdx`*
![Capture](https://user-images.githubusercontent.com/43018778/227825439-9b3b975e-43a4-4cdc-adfd-572a49620c50.PNG)

**Comment by imballinst** [comment]
hi @Thomas-Boi, thanks for catching it and for the suggestion! Yeah, I agree that the documentation of `TableRow` could be improved so it's consistent with the TypeScript typings. I forgot to add that prop to the JSDoc documentation 🤦

I'll work on it sometimes tonight or tomorrow.

**Comment by imballinst** [comment]
This should be updated in the newest version 3.9.1. Details can be seen in this section: https://github.com/imballinst/react-bs-datatable/blob/v3.9.1/api/modules/components_TableBody.md#tablerow.

Let me know if you have more feedback. Thanks for the report!
