### ISSUE TITLE
Feature Request: Clear checkbox state across data changes

### ISSUE THREAD

**Issue by Thomas-Boi** [imballinst/react-bs-datatable#173]
Hello again imballinst 👋 ,

Thank you for your time and sorry to bother you again. I run into a minor set back with the clear feature of `createBulkCheckboxClickHandler`. My project uses pagination from the backend and your table works great with selecting across pages. However, when clearing all of them, the checkboxes are not clear across pages. You can see the [sandbox](https://codesandbox.io/s/blissful-brattain-8q97mr?file=/src/App.js) for more details. To replicate:

- Select a few rows on page 1
- Go to page 2
- Select a few rows
- Verify that the selection works across pages by moving back and forth between pages.
- Press clear selection while on page 2 => only the rows on page 2 are cleared. Page 1 is still selected.

I tried to look for a place to reset the `checkbox.checkbox.selected` to `new Set()` but I couldn't find a clean way to do it. I'd appreciate your help on this 😄  . Let me know if I can assist with this in any way.

**Comment by Thomas-Boi** [comment]
I just added #174 which might do the job. I'm new to the code base so feel free to edit as you'd like.

**Comment by imballinst** [comment]
Released in https://www.npmjs.com/package/react-bs-datatable/v/3.10.0.
