### ISSUE TITLE
How to set  filter search box placeholder

### ISSUE THREAD

**Issue by satheesh1997** [Imballinst/react-bs-datatable#18]

**Comment by Imballinst** [comment]
Currently there isn't one. How about if it's set up in the `labels` prop? So it's like:

```js
<Datatable
  labels={{
    filterPlaceholder: 'Search input here...'
  }}
/>
```

**Comment by Imballinst** [comment]
Does this satisfy your needs? https://codesandbox.io/s/j4pwq6nlyw @satheesh1997

**Comment by satheesh1997** [comment]
Yes @Imballinst  it works

**Comment by Imballinst** [comment]
Merged the PR. Please re-install the package with version `1.2.5` (it should be 1.2.4 but I messed up the beta versioning earlier)
