### ISSUE TITLE
Can you please give me the pagination code?

### ISSUE THREAD

**Issue by RanjithaRaja** [Imballinst/react-bs-datatable#33]
Hi, 

I Am trying to implement lazy loading in the data table. I need a pagination code to complete that work.

Can you please provide the code?

**Comment by Imballinst** [comment]
Hey, unfortunately I don't have the lazy loading feature yet :frowning_face: it's been quite a while since https://github.com/Imballinst/react-bs-datatable/issues/1.

But if you have extended the table yourself, I think you can play around it in many ways.

**Comment by Imballinst** [comment]
Fixed with https://github.com/Imballinst/react-bs-datatable/pull/40.
