### ISSUE TITLE
How to add column button ?

### ISSUE THREAD

**Issue by cgarrotti** [Imballinst/react-bs-datatable#34]
How to add column button ?

**Comment by Imballinst** [comment]
Could you give a bit more clarification?

1. Use button in a column,
2. Implement "Add button" in a certain part of the table
3. Else?

Thanks!

**Comment by cgarrotti** [comment]
I need add a column button and how to trigger this button too

Em seg, 17 de jun de 2019 22:55, Try Ajitiono <notifications@github.com>
escreveu:

**Comment by Imballinst** [comment]
Hey, sorry for the late reply.

Just in case you're still working on it: https://codesandbox.io/s/128-issue-34-u9wvg. See line 154-174, when you click on a button on the most-right, it will trigger an alert.
