### ISSUE TITLE
Sorting only works with current active page instead of all pages

### ISSUE THREAD

**Issue by vijaypatoliya** [Imballinst/react-bs-datatable#46]
As now sorting only support with the current page. Is there an option to sort on the whole data source instead of a current active page?

Thanks in advance.

**Comment by Imballinst** [comment]
Sorry for that! I believe that should be a bug (and quite an annoying one!). I will inspect this and push a fix after real soon.

**Comment by Imballinst** [comment]
@vijaypatoliya This PR https://github.com/Imballinst/react-bs-datatable/pull/47 is an attempt to fix this issue. Please try out the sandbox https://codesandbox.io/s/serverless-cookies-6pgn3 and try to sort the "Score" column!

If the behavior is correct, I'll merge it and publish `2.0.3`.
