### ISSUE TITLE
How to add onClick event to a row?

### ISSUE THREAD

**Issue by henok-tesfaye** [Imballinst/react-bs-datatable#51]
I want to add a click event to a row of one column?

**Comment by Imballinst** [comment]
hey, sorry for the long reply. Let me know if this is enough: https://codesandbox.io/s/205-row-onclick-event-ev9oy

If yes, I'll merge #53 after few some commits (regarding docs, etc.)

**Comment by henok-tesfaye** [comment]
Yes @Imballinst , Issue fixed!

**Comment by Imballinst** [comment]
@henok-tesfaye this should be live in `react-bs-datatable@2.0.5` (updated the last sandbox, too). Let me know if something doesn't work!

**Comment by henok-tesfaye** [comment]
Thanks you @Imballinst. How long will it take to be released?
Sure I'll let you know.

**Comment by Imballinst** [comment]
@henok-tesfaye it should be live already: https://www.npmjs.com/package/react-bs-datatable

```
npm install react-bs-datatable@latest

# or
yarn add react-bs-datatable@latest
```

**Comment by henok-tesfaye** [comment]
Awesome, thanks @Imballinst !
