### ISSUE TITLE
How to add actions buttons for each Row

### ISSUE THREAD

**Issue by masnoonmulla** [Imballinst/react-bs-datatable#52]
I want to add edit and delete button for each row with its data and onClick event fire...

**Comment by FilippeMafra** [comment]
Hello @masnoonmulla,

If all the rows have the same button look at the link: https://github.com/Imballinst/react-bs-datatable/issues/15

**Comment by masnoonmulla** [comment]
Hi @FilippeMafra 
Thanks for your response
 Its work for me.
