### ISSUE TITLE
Custom Pagination position in 2.0.5-alpha.2

### ISSUE THREAD

**Issue by masnoonmulla** [Imballinst/react-bs-datatable#54]
I needed pagination position in bottom right and need to display current entries... IN V.2.0.5-alpha.2

**Comment by Imballinst** [comment]
Does this fit your need? https://imballinst.github.io/react-bs-datatable/?path=/story/advanced-guides--extending-the-table

You'll need to "compose" the table a bit -- but at the end of the day, it will result in the same experience.

**Comment by masnoonmulla** [comment]
Thank You @Imballinst ... 
 Displaying {(currentPage - 1) * rowsPerPage + 1}
                   to{" "}  {(currentPage - 1) * rowsPerPage + data.length} of{" "} {data.length} entries
I need a small help in this code how to display total entries in above code..
![dataTAble](https://user-images.githubusercontent.com/36194265/74634422-d25e8280-5189-11ea-8b8d-5f9e94cf844c.PNG)

**Comment by Imballinst** [comment]
@masnoonmulla could you try this? so instead of `data.length` -- use `props.tableBody.length`.

It's because `data` returned from `useTableLifecycle` is the data that we have sorted, filtered, and paginated. `props.tableBody` contains the "raw" data that you pass to the table. Let me know if this works!

**Comment by masnoonmulla** [comment]
Thank You so much @Imballinst for your help.. Its work

**Comment by Imballinst** [comment]
Awesome @masnoonmulla! Let me know if you need further help.

**Comment by masnoonmulla** [comment]
Yeah sir how to pass mulitple prop in headers array

**Comment by Imballinst** [comment]
oooh -- that. Unfortunately currently this library doesn't support column spanning (yet). But that is a good idea. Let's track it in different issue.
