### ISSUE TITLE
Remove Paging options and pagination form table

### ISSUE THREAD

**Issue by Swarna-Jain** [Imballinst/react-bs-datatable#6]
Ho can I remove or hide pagination and paging options in data table?

**Comment by Imballinst** [comment]
I actually set it in the `defaultProps`.
```
Datatable.defaultProps = {
  tableClass: '',
  rowsPerPage: 5,
  rowsPerPageOption: [5, 10, 15, 20],
  initialSort: undefined,
};
```
Yeah, I think you're right, I should have made a way for people who want their whole data appear without pagination. I think it this way: we need to pass `undefined` to `rowsPerPage` and `rowsPerPageOption` to disable the table pagination. What do you think?

**Comment by Swarna-Jain** [comment]
If it is being done at the time of implementation (rowsPerPage ={undefined} & rowsPerPageOption={undefined} Datatable assumes default.. I actually want to hide both of the options from Data table display rather than disable only... if it is possible to put control over  visibility. like .. pagination = "disabled" or pagination = {false} and pagination will be disappeared. as well as rowsPerPageOption and rowsPerPage options will become undefined or null.

**Comment by Imballinst** [comment]
Um, I mean, I set them (`defaultProps.rowsPerPage` and `defaultProps.rowsPerPageOption`) to `undefined` too. I think it's cleaner than adding a new props, because if someone doesn't define rows per page and rows per page option props, that means he/she doesn't want to use the pagination, isn't it?

**Comment by Swarna-Jain** [comment]
That's cool ...

**Comment by Imballinst** [comment]
Okay, I'll work on it soon!

**Comment by Swarna-Jain** [comment]
Thanks

**Comment by Imballinst** [comment]
Hi, kindly check my PR: https://github.com/Imballinst/react-bs-datatable/pull/7
If you want to test it live: https://imballinst.github.io/react-bs-datatable/beta/1.1.12/

**Comment by Swarna-Jain** [comment]
It's exact what I want...

**Comment by Imballinst** [comment]
Alright, I'll merge the branch and I'll publish it to NPM after, should you have any more suggestions/issues, feel free to file another issue! :)
