### ISSUE TITLE
How do i start?

### ISSUE THREAD

**Issue by Itedjere** [imballinst/react-bs-datatable#62]
I am confused on how to start using it. I have installed it. But how to start

Do i have to use the storybook pattern like you did in the examples.

Please guide me or show me resources to read on how to start.

Thanks

**Comment by Imballinst** [comment]
hello! sorry for the late reply. I also just realized that there is no "Usage" section in the README. I'll try to add that. You don't have to use Storybook, for example, to use it in your React app, you can use this:

```
import React from 'react';
import moment from 'moment';
import Datatable from 'react-bs-datatable';

const header = [
  { title: 'Username', prop: 'username' },
  { title: 'Name', prop: 'realname' },
  { title: 'Location', prop: 'location' },
  { title: 'Last Updated', prop: 'date' }
];

const body = Array.from(new Array(57), () => {
  const rd = (Math.random() * 10).toFixed(1);

  if (rd > 0.5) {
    return {
      username: 'i-am-billy',
      realname: `Billy ${rd}`,
      location: 'Mars',
      date: moment()
        .subtract(1, 'days')
        .format('Do MMMM YYYY')
    };
  }

  return {
    username: 'john-nhoj',
    realname: `John ${rd}`,
    location: 'Saturn',
    date: moment()
      .subtract(2, 'days')
      .format('Do MMMM YYYY')
  };
});

const Table = () => (
  <Datatable
    tableHeaders={header}
    tableBody={body}
  />
));
```

**Comment by Itedjere** [comment]
Wow thank you so much

This really helps me as a beginning 😂

Thanks.

Itedjere Godspower

**Comment by Imballinst** [comment]
all good @Itedjere! Please let me know if you have further questions 👍
