### ISSUE TITLE
npm audit node-fetch vulnerability

### ISSUE THREAD

**Issue by shareef** [imballinst/react-bs-datatable#76]
Low             Denial of Service

  Package         node-fetch

  Patched in      >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9

  Dependency of   react-bs-datatable

  Path            react-bs-datatable > react-bootstrap >
                  @react-bootstrap/react-popper > create-react-context > fbjs
                  > isomorphic-fetch > node-fetch

  More info       https://npmjs.com/advisories/1556

**Comment by Imballinst** [comment]
Thanks for reporting! I'm going to bump `react-bootstrap` to fix this issue.
