### ISSUE TITLE
Invest in CI tooling for testing and ensuring 0 discrepancies

### ISSUE THREAD

**Issue by imballinst** [imballinst/react-bs-datatable#81]
Previously we have this TravisCI thing, but since its migration, the hook couldn't work and hence I disabled it. I'll probably need to do 2 things:

1. Set up a CI. In this CI, run all unit tests, and check if `yarn build` updates a new file in `git status`. If it has new untracked files, then fail the build.
2. Run it in PRs and `master` branch.
3. Would probably be awesome if every tag from Github Releases is released automatically to NPM but I don't know about this since publishing to NPM requires credentials.

**Comment by KapitanOczywisty** [comment]
Github Actions is pretty good ;)

I'm a bit confused about 1, what are you trying to test?

3. You can easily deploy to npm, github have secret tokens built in: https://gomakethings.com/how-to-automate-npm-deployment-with-github-action-hooks/

**Comment by Imballinst** [comment]
@KapitanOczywisty yes, but it's only for `master`, isn't it? We can't run GitHub Actions on non-master branch (last I checked).

As for (1), it's about what you said earlier about updating `lib`. It's technically to ensure that `lib` is always up to date (e.g. so that I don't mistakenly publish a version with stale `lib` folder).

**Comment by KapitanOczywisty** [comment]
> @KapitanOczywisty yes, but it's only for `master`, isn't it? We can't run GitHub Actions on non-master branch (last I checked).

I've never heard about that, but even If it was the case in the past, it's not anymore.

> As for (1), it's about what you said earlier about updating `lib`. It's technically to ensure that `lib` is always up to date (e.g. so that I don't mistakenly publish a version with stale `lib` folder).

Right. I've seen somewhere lately build auto committed on reviewed pull-request. Basically you're setting label `automerge` etc and Actions will build, commit and merge PR. Probably: https://github.com/EndBug/add-and-commit + https://github.com/pascalgn/automerge-action
